[package]
name = "cargo-xtask"
version = "0.1.0"
edition = "2021"
authors = ["egg Maintainers"]

[[bin]]
name = "cargo-xtask"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
xshell = "0.2"
